"""empty message

Revision ID: 0b2034870e19
Revises: 81073a4dbeb5
Create Date: 2020-03-02 16:38:29.737984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b2034870e19'
down_revision = '81073a4dbeb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'event', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event', type_='unique')
    # ### end Alembic commands ###
