"""empty message

Revision ID: 43afb57cd237
Revises: 67980cde6e0a
Create Date: 2020-03-07 16:07:36.714733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43afb57cd237'
down_revision = '67980cde6e0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challonge_player', sa.Column('bracket_id', sa.Integer(), nullable=False))
    op.drop_constraint('challonge_player_challonge_id_key', 'challonge_player', type_='unique')
    op.create_foreign_key(None, 'challonge_player', 'bracket', ['bracket_id'], ['bracket_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'challonge_player', type_='foreignkey')
    op.create_unique_constraint('challonge_player_challonge_id_key', 'challonge_player', ['challonge_id'])
    op.drop_column('challonge_player', 'bracket_id')
    # ### end Alembic commands ###
