"""empty message

Revision ID: 4bd6847c458c
Revises: 63b69d0fd3af
Create Date: 2020-03-06 22:47:13.882246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bd6847c458c'
down_revision = '63b69d0fd3af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'challonge_player', ['challonge_id'])
    op.create_unique_constraint(None, 'event', ['id'])
    op.create_unique_constraint(None, 'player', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'player', type_='unique')
    op.drop_constraint(None, 'event', type_='unique')
    op.drop_constraint(None, 'challonge_player', type_='unique')
    # ### end Alembic commands ###
