"""empty message

Revision ID: 4e5a52d1a034
Revises: 245f535c8d0a
Create Date: 2020-03-02 16:27:13.931844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e5a52d1a034'
down_revision = '245f535c8d0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('event_user_id_fkey', 'event', type_='foreignkey')
    op.drop_column('event', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('event_user_id_fkey', 'event', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
