"""empty message

Revision ID: 63b69d0fd3af
Revises: 2453f12ec63c
Create Date: 2020-03-02 16:55:09.843906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63b69d0fd3af'
down_revision = '2453f12ec63c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'bracket', ['id'])
    op.create_unique_constraint(None, 'player', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'player', type_='unique')
    op.drop_constraint(None, 'bracket', type_='unique')
    # ### end Alembic commands ###
