"""empty message

Revision ID: 67980cde6e0a
Revises: 4bd6847c458c
Create Date: 2020-03-06 22:49:47.374616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67980cde6e0a'
down_revision = '4bd6847c458c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'bracket', ['bracket_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bracket', type_='unique')
    # ### end Alembic commands ###
