"""empty message

Revision ID: 6cbaa104d1ae
Revises: d1643333ca9c
Create Date: 2020-02-09 13:52:31.194073

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6cbaa104d1ae'
down_revision = 'd1643333ca9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('players', sa.JSON(), nullable=True))
    op.drop_column('event', 'list_of_players')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('list_of_players', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('event', 'players')
    # ### end Alembic commands ###
