"""empty message

Revision ID: 81073a4dbeb5
Revises: 4e5a52d1a034
Create Date: 2020-03-02 16:28:58.131342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81073a4dbeb5'
down_revision = '4e5a52d1a034'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bracket_event_id_fkey', 'bracket', type_='foreignkey')
    op.drop_column('bracket', 'event_id')
    op.drop_constraint('event_id_key', 'event', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('event_id_key', 'event', ['id'])
    op.add_column('bracket', sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('bracket_event_id_fkey', 'bracket', 'event', ['event_id'], ['id'])
    # ### end Alembic commands ###
