"""empty message

Revision ID: f423efd76c4d
Revises: ba618305b2d0
Create Date: 2020-02-28 16:52:43.605828

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f423efd76c4d'
down_revision = 'ba618305b2d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bracket_players',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('bracket_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['bracket_id'], ['bracket.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('player_id', 'bracket_id')
    )
    op.drop_table('bracket__players')
    op.drop_column('event', 'players')
    op.drop_column('event', 'brackets')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('brackets', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('players', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_table('bracket__players',
    sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bracket_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['bracket_id'], ['bracket.id'], name='bracket__players_bracket_id_fkey'),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], name='bracket__players_player_id_fkey'),
    sa.PrimaryKeyConstraint('player_id', 'bracket_id', name='bracket__players_pkey')
    )
    op.drop_table('bracket_players')
    # ### end Alembic commands ###
